CREATE TABLE users (
id serial PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password_hash VARCHAR(255) NOT NULL,
created_at TIMESTAMPTZ DEFAULT NOW()
);

SELECT * FROM users;

TRUNCATE TABLE users RESTART IDENTITY

DELETE FROM users